const ChannelInfo = require('./ChannelInfo');

module.exports = {
	"das_erste": new ChannelInfo("https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8"),
	"zdf": new ChannelInfo("http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8"),
	"arte": new ChannelInfo("http://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8"),
	"dreisat": new ChannelInfo("http://zdf0910-lh.akamaihd.net/i/dach10_v1@392872/master.m3u8"),
	"kika": new ChannelInfo("https://kikade-lh.akamaihd.net/i/livetvkika_de@450035/master.m3u8"),
	"phoenix": new ChannelInfo("http://zdf0910-lh.akamaihd.net/i/de09_v1@392871/master.m3u"),
	"tagesschau24": new ChannelInfo("http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/master.m3u8"),
	"ard_alpha": new ChannelInfo("http://livestreams.br.de/i/bralpha_germany@119899/master.m3u8"),
	"zdf_info": new ChannelInfo("http://zdf1112-lh.akamaihd.net/i/de12_v1@392882/master.m3u8"),
	"zdf_neo": new ChannelInfo("http://zdf1314-lh.akamaihd.net/i/de13_v1@392877/master.m3u8"),
	"deutsche_welle": new ChannelInfo("http://dwstream72-lh.akamaihd.net/i/dwstream72_live@123556/master.m3u8"),
	"deutsche_welle_plus": new ChannelInfo("https://dwstream52-lh.akamaihd.net/i/dwstream52_live@500528/index_1_av-p.m3u8"),
	"one": new ChannelInfo("http://onelivestream-lh.akamaihd.net/i/one_livestream@568814/master.m3u8"),
	"br_nord": new ChannelInfo("http://livestreams.br.de/i/bfsnord_germany@119898/master.m3u8"),
	"br_sued": new ChannelInfo("http://livestreams.br.de/i/bfssued_germany@119890/master.m3u8"),
	"hr": new ChannelInfo("http://livestream-1.hr.de/i/hr_fernsehen@75910/master.m3u8"),
	"mdr_sachsen": new ChannelInfo("http://mdrsnhls-lh.akamaihd.net/i/livetvmdrsachsen_de@513998/master.m3u8"),
	"mdr_sachsen_anhalt": new ChannelInfo("http://mdrsahls-lh.akamaihd.net/i/livetvmdrsachsenanhalt_de@513999/master.m3u8"),
	"mdr_thueringen": new ChannelInfo("http://mdrthuhls-lh.akamaihd.net/i/livetvmdrthueringen_de@514027/master.m3u8"),
	"ndr_hh": new ChannelInfo("https://ndrfs-lh.akamaihd.net/i/ndrfs_hh@430231/master.m3u8"),
	"ndr_mv": new ChannelInfo("https://ndrfs-lh.akamaihd.net/i/ndrfs_mv@430232/master.m3u8"),
	"ndr_nds": new ChannelInfo("https://ndrfs-lh.akamaihd.net/i/ndrfs_nds@430233/master.m3u8"),
	"ndr_sh": new ChannelInfo("https://ndrfs-lh.akamaihd.net/i/ndrfs_sh@430234/master.m3u8"),
	"rbb_berlin": new ChannelInfo("https://rbblive-lh.akamaihd.net/i/rbb_berlin@144674/master.m3u8"),
	"rbb_brandenburg": new ChannelInfo("https://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/master.m3u8"),
	"sr": new ChannelInfo("http://live2_sr-lh.akamaihd.net/i/sr_universal02@107595/master.m3u8"),
	"swr_bw": new ChannelInfo("https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master.m3u8"),
	"swr_rp": new ChannelInfo("https://swrrphls-i.akamaihd.net/hls/live/667639/swrrpd/master.m3u8"),
	"wdr": new ChannelInfo("http://wdrfsgeo-lh.akamaihd.net/i/wdrfs_geogeblockt@530016/master.m3u8"),
	"parlamentsfernsehen_1": new ChannelInfo("https://cldf-hlsgw.r53.cdn.tv1.eu/1000153copo/hk1.m3u8"),
	"parlamentsfernsehen_2": new ChannelInfo("https://cldf-hlsgw.r53.cdn.tv1.eu/1000153copo/hk2.m3u8"),
};
